### PR TITLE
Split server services

### LINKED ISSUE #65: Separate letter detection and hand recognition
Right now - 
Frames are being sent to the server and undergoing all detections.
1. Either we send lots of FPS and then the server crashes
2. Or we send a small amount and then the user feels a big delay.

Thing is, the rectangle recognition, which is what the user is expecting to flow, is cheap. And the letter recognition, which doesnt even have to flow, is expensive.
What we need - 
Separate the server to accommodate 2 services: Hand recognition (get_rect) and letter detection (process_image).
After that, make the application ask for hand recognition in a high pace, and letter detection in a lower pace.
Giving the user a good flow, while not crashing the server

### PR DESCRIPTION
**Pull request by chai00xxdd**
1.split the img api in the ts server to two apis (one for detect hands,one for detect sign +hands cus detect hands is cheap anyway)
2.updated the signifyService.py ==> now its recive request (hands, hands+sign) and the img as input
      if request = hands its return only the rectangle of the hands
      if request = hands+sign its return the reactangle of the hands + detecing the sign 
3. updated the reactNative  to support the two apis 
  now the frameProcessorFps property of signifyCamera works like that:
   the first and the last frame it will detect hands + sign (which is expensive)
   and in the middle frames it will detect only the reactangle/
example: frameProcessorFps = 5
 first frame it will detect hands + sign , 3 frames letter only hands , last frame hands + sign again
**** in the future i will allow to send more hands + sign requests by paremter and not fix to the first and last frame.
fix #65

### CODE REVIEW

**Review by Micha546 — CHANGES_REQUESTED** [review]
Overall I think that it can be better to split the python services to 2 instead of passing a request string each time, 1 service will only provide sign detection and the others will provide hand detection, this way we don't need to change the whole pool object and can just use 2 pools.
The thing is that im not sure running the sign detection on the gpu and the hand detection on the cpu will result in good times, we need to try it and then decide.

**Comment by Micha546** [comment]
Maybe marge only the camera commit for now, and we can decide which way is better after we see how the 2 seperate services work

**Comment by chai00xxdd** [comment]
> Maybe only marge the camera commit for now, and we can decide which way is better after we see how the 2 seperate services work

hmm. i dont think its that big deal we can do it later seperate to two pythons services
anyway you can use two pools now
just for the first pool you will send the request DetectType.Hands
and the second one DetectType.signHands.

so the only diffrence is that now the pyProcess assume the the python file he runs
recive request and data (which i think is more maintablity ),
anyway the changes in the app are counted on the changes in the server (two new apis and so on).
so i think its better to merge this one (the two pools is possible anyway)
and if you want to make two python files one for hands recognize and one for sign recognize
with out request we can just send request = "",
or remove the request when we create the two pools
anyway i thogut of it and i am not sure if running one pool on the cpu is such good idea
cus on the cpu hand recognize can take about 100ms or even more and we want to use it much faster
so we can do atlist 12 of it in a second.

**Comment by Micha546** [comment]
> > Maybe only marge the camera commit for now, and we can decide which way is better after we see how the 2 seperate services work
> 
> hmm. i dont think its that big deal we can do it later seperate to two pythons services anyway you can use two pools now just for the first pool you will send the request DetectType.Hands and the second one DetectType.signHands.
> 
> so the only diffrence is that now the pyProcess assume the the python file he runs recive request and data (which i think is more maintablity ), anyway the changes in the app are counted on the changes in the server (two new apis and so on). so i think its better to merge this one (the two pools is possible anyway) and if you want to make two python files one for hands recognize and one for sign recognize with out request we can just send request = "", or remove the request when we create the two pools anyway i thogut of it and i am not sure if running one pool on the cpu is such good idea cus on the cpu hand recognize can take about 100ms or even more and we want to use it much faster so we can do atlist 12 of it in a second.

I built my commit on your commit (the commit that changed the camera-app) so it works good I think, ( I copied the structure that you had for the signifyApi too ).
Anyway - I tried it on my computer (one service running on gpu and 5 on cpu) and it works great for me - much faster than alot of requests for the gpu - check my PR out and tell me what you think (tried it with the fetch_debug.js script - not with the phone)
I'm not happy with the signifyService in general - I think its a bit messy - for now I just use the useCuda to decide if I want to detect the sign or not.. but I think that neither this solution nor the request string are particularly clean.

**Comment by chai00xxdd** [comment]
this pull request is dead
and #71  replace it

**Pull request closed without merging**
